### ISSUE TITLE
fisherman

### ISSUE THREAD

**Issue by ghost** [iampeterbanjo/omf_config#1]
Hi @iampeterbanjo, I'm no longer maintaining omf, and would appreciate a ton if you can upgrade to fisherman:
• fisherman/fisherman#69 (comment)

I can lend a hand too if you need help with anything

**Comment by iampeterbanjo** [comment]
Thanks for the heads up. I've been using both but I didn't realise omf was no longer maintained :-)

**Comment by ghost** [comment]
Thanks!

I meant, _I'm_ not maintaining the project anymore. Also, all [new plugins and themes](https://github.com/fisherman) are not compatible with oh-my-fish either. However, fisherman can run all previous omf stuff okay :)
